In [1]:
from src import functions as f

import pandas as pd
import numpy as np

In [2]:
 X_train, X_test, y_train, y_test, stock_df, current_price = f.data('aapl', "12/12/1980", 1)

In [3]:
stock_df.sample(5)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,month,dayofweek,oc,...,8stdev_adj,8sma_adj,8sma_close,13stdev_adj,13sma_adj,13sma_close,21stdev_adj,21sma_adj,21sma_close,direction
Date,,,,,,,,,,,,,,,,,,,,,
1999-12-21,0.750673,0.787944,0.748762,0.783644,307596800,0.0,0.0,12,1,0.043922,...,0.031901,-0.002858,1,0.035750,-0.004952,1,0.035529,0.005534,1,-1
2000-01-27,0.831905,0.863920,0.818047,0.840984,340144000,0.0,0.0,1,3,0.010914,...,0.039438,0.012106,1,0.050851,0.008917,1,0.053532,0.006785,1,-1
1996-02-12,0.215024,0.217891,0.214069,0.216935,194275200,0.0,0.0,2,0,0.008888,...,0.025646,0.003644,1,0.034157,-0.009248,1,0.034896,-0.007808,1,-1
2013-04-04,13.460706,13.499185,13.196618,13.273268,358447600,0.0,0.0,4,3,-0.013925,...,0.013276,-0.009489,1,0.015935,-0.002693,1,0.015604,-0.000263,1,-1
1981-12-31,0.077207,0.077643,0.077207,0.077207,54656000,0.0,0.0,12,3,0.000000,...,0.031028,-0.003735,1,0.043121,0.013657,1,0.035056,0.008807,1,-1

In [4]:
stock_df = pd.read_pickle(f'./data/aapl_df.pkl')

In [5]:
stock_df.tail(5)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-01-31,169.943485,174.777323,169.294303,174.557602,115541600,0.00,0.0
2022-02-01,173.788575,174.617520,172.090741,174.387817,86213900,0.00,0.0
2022-02-02,174.527647,175.656214,173.109456,175.616257,84914300,0.00,0.0
2022-02-03,174.257984,176.015754,171.900986,172.679993,89418100,0.00,0.0
2022-02-04,171.679993,174.100006,170.679993,172.389999,82391400,0.22,0.0

In [6]:
df_sample = stock_df[['Close', 'Volume']].iloc[-39:]
df_sample

                 Close     Volume
Date
2021-12-10  179.221664  115228100
2021-12-13  175.516388  153237000
2021-12-14  174.108185  139380400
2021-12-15  179.071854  131063300
2021-12-16  172.040802  150185800
2021-12-17  170.922241  195432700
2021-12-20  169.533997  107499100
2021-12-21  172.769882   91185900
2021-12-22  175.416504   92135300
2021-12-23  176.055695   68356600
2021-12-27  180.100540   74919600
2021-12-28  179.061859   79144300
2021-12-29  179.151749   62348900
2021-12-30  177.973251   59773000
2021-12-31  177.344055   64062300
2022-01-03  181.778397  104487900
2022-01-04  179.471344   99310400
2022-01-05  174.697418   94537600
2022-01-06  171.781143   96904000
2022-01-07  171.950928   86580100
2022-01-10  171.970901  106765600
2022-01-11  174.857224   76138300
2022-01-12  175.306641   74805200
2022-01-13  171.970901   84505800
2022-01-14  172.849792   80355000
2022-01-18  169.583939   90956700
2022-01-19  166.018478   94815000
2022-01-20  164.300659   91420500
2022-01-21  162.203354  122848900
2022-01-24  161.414337  162294600
2022-01-25  159.576691  115798400
2022-01-26  159.486801  108275300
2022-01-27  159.017410  121954600
2022-01-28  170.113266  179935700
2022-01-31  174.557602  115541600
2022-02-01  174.387817   86213900
2022-02-02  175.616257   84914300
2022-02-03  172.679993   89418100
2022-02-04  172.389999   82391400

In [7]:
df_sample['roll'] = [x.to_list() for x in df_sample.Close.rolling(window=3)]

In [8]:
df_sample

,Close,Volume,roll
Date,,,
2021-12-10,179.221664,115228100,[179.22166442871094]
2021-12-13,175.516388,153237000,"[179.22166442871094, 175.51638793945312]"
2021-12-14,174.108185,139380400,"[179.22166442871094, 175.51638793945312, 174.1..."
2021-12-15,179.071854,131063300,"[175.51638793945312, 174.10818481445312, 179.0..."
2021-12-16,172.040802,150185800,"[174.10818481445312, 179.0718536376953, 172.04..."
2021-12-17,170.922241,195432700,"[179.0718536376953, 172.04080200195312, 170.92..."
2021-12-20,169.533997,107499100,"[172.04080200195312, 170.9222412109375, 169.53..."
2021-12-21,172.769882,91185900,"[170.9222412109375, 169.53399658203125, 172.76..."
2021-12-22,175.416504,92135300,"[169.53399658203125, 172.76988220214844, 175.4..."
2021-12-23,176.055695,68356600,"[172.76988220214844, 175.41650390625, 176.0556..."
2021-12-27,180.100540,74919600,"[175.41650390625, 176.05569458007812, 180.1005..."
2021-12-28,179.061859,79144300,"[176.05569458007812, 180.1005401611328, 179.06..."
2021-12-29,179.151749,62348900,"[180.1005401611328, 179.06185913085938, 179.15..."
2021-12-30,177.973251,59773000,"[179.06185913085938, 179.15174865722656, 177.9..."
2021-12-31,177.344055,64062300,"[179.15174865722656, 177.97325134277344, 177.3..."
2022-01-03,181.778397,104487900,"[177.97325134277344, 177.34405517578125, 181.7..."
2022-01-04,179.471344,99310400,"[177.34405517578125, 181.7783966064453, 179.47..."
2022-01-05,174.697418,94537600,"[181.7783966064453, 179.47134399414062, 174.69..."
2022-01-06,171.781143,96904000,"[179.47134399414062, 174.69741821289062, 171.7..."
2022-01-07,171.950928,86580100,"[174.69741821289062, 171.78114318847656, 171.9..."
2022-01-10,171.970901,106765600,"[171.78114318847656, 171.950927734375, 171.970..."
2022-01-11,174.857224,76138300,"[171.950927734375, 171.9709014892578, 174.8572..."
2022-01-12,175.306641,74805200,"[171.9709014892578, 174.8572235107422, 175.306..."
2022-01-13,171.970901,84505800,"[174.8572235107422, 175.306640625, 171.9709014..."
2022-01-14,172.849792,80355000,"[175.306640625, 171.9709014892578, 172.8497924..."
2022-01-18,169.583939,90956700,"[171.9709014892578, 172.84979248046875, 169.58..."
2022-01-19,166.018478,94815000,"[172.84979248046875, 169.5839385986328, 166.01..."
2022-01-20,164.300659,91420500,"[169.5839385986328, 166.0184783935547, 164.300..."
2022-01-21,162.203354,122848900,"[166.0184783935547, 164.3006591796875, 162.203..."
2022-01-24,161.414337,162294600,"[164.3006591796875, 162.20335388183594, 161.41..."
2022-01-25,159.576691,115798400,"[162.20335388183594, 161.41433715820312, 159.5..."
2022-01-26,159.486801,108275300,"[161.41433715820312, 159.57669067382812, 159.4..."
2022-01-27,159.017410,121954600,"[159.57669067382812, 159.48680114746094, 159.0..."
2022-01-28,170.113266,179935700,"[159.48680114746094, 159.0174102783203, 170.11..."
2022-01-31,174.557602,115541600,"[159.0174102783203, 170.11326599121094, 174.55..."
2022-02-01,174.387817,86213900,"[170.11326599121094, 174.55760192871094, 174.3..."
2022-02-02,175.616257,84914300,"[174.55760192871094, 174.3878173828125, 175.61..."
2022-02-03,172.679993,89418100,"[174.3878173828125, 175.6162567138672, 172.679..."
2022-02-04,172.389999,82391400,"[175.6162567138672, 172.67999267578125, 172.38..."

In [9]:
x = [1, 2, 3]
y = [2, 4, 6]
slope = np.polyfit(x,y,1)[0]
slope

1.9999999999999996

In [10]:
def slope3(x, y):
    return np.polyfit(x, y, 1)[0]

In [11]:
df_sample['slope3'] = df_sample.iloc[2:].apply(lambda x: slope3(x.roll, [1, 2, 3]), axis=1)

In [12]:
df_sample

,Close,Volume,roll,slope3
Date,,,,
2021-12-10,179.221664,115228100,[179.22166442871094],NaN
2021-12-13,175.516388,153237000,"[179.22166442871094, 175.51638793945312]",NaN
2021-12-14,174.108185,139380400,"[179.22166442871094, 175.51638793945312, 174.1...",-0.366472
2021-12-15,179.071854,131063300,"[175.51638793945312, 174.10818481445312, 179.0...",0.271670
2021-12-16,172.040802,150185800,"[174.10818481445312, 179.0718536376953, 172.04...",-0.079162
2021-12-17,170.922241,195432700,"[179.0718536376953, 172.04080200195312, 170.92...",-0.208781
2021-12-20,169.533997,107499100,"[172.04080200195312, 170.9222412109375, 169.53...",-0.794762
2021-12-21,172.769882,91185900,"[170.9222412109375, 169.53399658203125, 172.76...",0.350553
2021-12-22,175.416504,92135300,"[169.53399658203125, 172.76988220214844, 175.4...",0.338858
2021-12-23,176.055695,68356600,"[172.76988220214844, 175.41650390625, 176.0556...",0.541328
2021-12-27,180.100540,74919600,"[175.41650390625, 176.05569458007812, 180.1005...",0.363014
2021-12-28,179.061859,79144300,"[176.05569458007812, 180.1005401611328, 179.06...",0.340621
2021-12-29,179.151749,62348900,"[180.1005401611328, 179.06185913085938, 179.15...",-1.432395
2021-12-30,177.973251,59773000,"[179.06185913085938, 179.15174865722656, 177.9...",-1.264841
2021-12-31,177.344055,64062300,"[179.15174865722656, 177.97325134277344, 177.3...",-1.073346
2022-01-03,181.778397,104487900,"[177.97325134277344, 177.34405517578125, 181.7...",0.330514
2022-01-04,179.471344,99310400,"[177.34405517578125, 181.7783966064453, 179.47...",0.216252
2022-01-05,174.697418,94537600,"[181.7783966064453, 179.47134399414062, 174.69...",-0.271464
2022-01-06,171.781143,96904000,"[179.47134399414062, 174.69741821289062, 171.7...",-0.255109
2022-01-07,171.950928,86580100,"[174.69741821289062, 171.78114318847656, 171.9...",-0.512510
2022-01-10,171.970901,106765600,"[171.78114318847656, 171.950927734375, 171.970...",8.726665
2022-01-11,174.857224,76138300,"[171.950927734375, 171.9709014892578, 174.8572...",0.519668
2022-01-12,175.306641,74805200,"[171.9709014892578, 174.8572235107422, 175.306...",0.509014
2022-01-13,171.970901,84505800,"[174.8572235107422, 175.306640625, 171.9709014...",-0.440436
2022-01-14,172.849792,80355000,"[175.306640625, 171.9709014892578, 172.8497924...",-0.410942
2022-01-18,169.583939,90956700,"[171.9709014892578, 172.84979248046875, 169.58...",-0.417889
2022-01-19,166.018478,94815000,"[172.84979248046875, 169.5839385986328, 166.01...",-0.292582
2022-01-20,164.300659,91420500,"[169.5839385986328, 166.0184783935547, 164.300...",-0.363725
2022-01-21,162.203354,122848900,"[166.0184783935547, 164.3006591796875, 162.203...",-0.522506
2022-01-24,161.414337,162294600,"[164.3006591796875, 162.20335388183594, 161.41...",-0.648510
2022-01-25,159.576691,115798400,"[162.20335388183594, 161.41433715820312, 159.5...",-0.723011
2022-01-26,159.486801,108275300,"[161.41433715820312, 159.57669067382812, 159.4...",-0.814404
2022-01-27,159.017410,121954600,"[159.57669067382812, 159.48680114746094, 159.0...",-3.100210
2022-01-28,170.113266,179935700,"[159.48680114746094, 159.0174102783203, 170.11...",0.134933
2022-01-31,174.557602,115541600,"[159.0174102783203, 170.11326599121094, 174.55...",0.121292
2022-02-01,174.387817,86213900,"[170.11326599121094, 174.55760192871094, 174.3...",0.336997
2022-02-02,175.616257,84914300,"[174.55760192871094, 174.3878173828125, 175.61...",1.194582
2022-02-03,172.679993,89418100,"[174.3878173828125, 175.6162567138672, 172.679...",-0.392682
2022-02-04,172.389999,82391400,"[175.6162567138672, 172.67999267578125, 172.38...",-0.506358

In [13]:
[x for x in range(1, 4)]

[1, 2, 3]