In [1]:
from src import functions as f

import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2

In [2]:
 X_train, X_test, y_train, y_test, stock_df, current_price = f.data('aapl', "12/12/1980", 1)

/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)
/home/oem/.local/lib/python3.8/site-packages/pandas/core/apply.py:290: RankWarning: Polyfit may be poorly conditioned
  results[i] = self.f(v)

In [3]:
stock_df.sample(5)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,month,dayofweek,oc,...,slope3,roll5,slope5,roll9,slope9,roll13,slope13,roll21,slope21,direction
Date,,,,,,,,,,,,,,,,,,,,,
2004-07-29,0.496486,0.501838,0.491287,0.499085,222157600,0.0,0.0,7,3,0.005236,...,199.452691,"[0.46942138671875, 0.47798433899879456, 0.4958...",113.930354,"[0.48884087800979614, 0.49235770106315613, 0.4...",88.433620,"[0.44679194688796997, 0.4522961676120758, 0.50...",109.927535,"[0.49755629897117615, 0.49388688802719116, 0.4...",107.679264,-1
2011-10-20,12.232487,12.243190,12.055422,12.089061,549270400,0.0,0.0,10,3,-0.011725,...,-2.041462,"[12.905275344848633, 12.843807220458984, 12.91...",-3.368675,"[11.890283584594727, 12.24135684967041, 12.299...",1.929772,"[11.391502380371094, 11.567346572875977, 11.54...",5.122440,"[12.288143157958984, 12.363990783691406, 12.32...",3.944720,1
1988-11-16,0.275149,0.276913,0.266331,0.268095,147840000,0.0,0.0,11,2,-0.025639,...,-208.889978,"[0.27867764234542847, 0.2716221213340759, 0.27...",-280.676235,"[0.26633113622665405, 0.2645667493343353, 0.27...",207.887318,"[0.2725040912628174, 0.2680947482585907, 0.262...",349.032469,"[0.28220507502555847, 0.2927878201007843, 0.28...",-425.427966,1
1998-05-11,0.236049,0.241783,0.235093,0.236527,665022400,0.0,0.0,5,0,0.002024,...,336.304866,"[0.22697004675865173, 0.23174811899662018, 0.2...",422.571549,"[0.20642289519309998, 0.2092904895544052, 0.21...",240.441740,"[0.21167953312397003, 0.21359074115753174, 0.2...",312.200562,"[0.20212261378765106, 0.20594508945941925, 0.2...",433.395648,-1
1990-03-28,0.300981,0.301877,0.293815,0.295607,102939200,0.0,0.0,3,2,-0.017856,...,-257.636947,"[0.2920231819152832, 0.3027726411819458, 0.302...",58.157062,"[0.2884403169155121, 0.30366840958595276, 0.29...",169.747550,"[0.2624628245830536, 0.26425427198410034, 0.26...",189.626603,"[0.2436511069536209, 0.2454434037208557, 0.241...",254.823816,1

In [4]:
stock_df = pd.read_pickle(f'./data/aapl_df.pkl')

In [5]:
stock_df.tail(5)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-02-04,171.679993,174.100006,170.679993,172.389999,82391400,0.22,0.0
2022-02-07,172.860001,173.949997,170.949997,171.660004,77251200,0.00,0.0
2022-02-08,171.729996,175.350006,171.429993,174.830002,74829200,0.00,0.0
2022-02-09,176.050003,176.649994,174.899994,176.279999,70195600,0.00,0.0
2022-02-10,174.139999,175.479996,172.520004,173.294998,59841088,0.00,0.0

In [6]:
df_sample = stock_df[['Close', 'Volume']].iloc[-39:]
df_sample

                 Close     Volume
Date
2021-12-16  172.040802  150185800
2021-12-17  170.922241  195432700
2021-12-20  169.533997  107499100
2021-12-21  172.769882   91185900
2021-12-22  175.416504   92135300
2021-12-23  176.055695   68356600
2021-12-27  180.100540   74919600
2021-12-28  179.061859   79144300
2021-12-29  179.151749   62348900
2021-12-30  177.973251   59773000
2021-12-31  177.344055   64062300
2022-01-03  181.778397  104487900
2022-01-04  179.471344   99310400
2022-01-05  174.697418   94537600
2022-01-06  171.781143   96904000
2022-01-07  171.950928   86580100
2022-01-10  171.970901  106765600
2022-01-11  174.857224   76138300
2022-01-12  175.306641   74805200
2022-01-13  171.970901   84505800
2022-01-14  172.849792   80355000
2022-01-18  169.583939   90956700
2022-01-19  166.018478   94815000
2022-01-20  164.300659   91420500
2022-01-21  162.203354  122848900
2022-01-24  161.414337  162294600
2022-01-25  159.576691  115798400
2022-01-26  159.486801  108275300
2022-01-27  159.017410  121954600
2022-01-28  170.113266  179935700
2022-01-31  174.557602  115541600
2022-02-01  174.387817   86213900
2022-02-02  175.616257   84914300
2022-02-03  172.679993   89418100
2022-02-04  172.389999   82391400
2022-02-07  171.660004   77251200
2022-02-08  174.830002   74829200
2022-02-09  176.279999   70195600
2022-02-10  173.294998   59841088

In [7]:
df_sample['roll'] = [x.to_list() for x in df_sample.Close.rolling(window=3)]

In [8]:
df_sample

,Close,Volume,roll
Date,,,
2021-12-16,172.040802,150185800,[172.04080200195312]
2021-12-17,170.922241,195432700,"[172.04080200195312, 170.9222412109375]"
2021-12-20,169.533997,107499100,"[172.04080200195312, 170.9222412109375, 169.53..."
2021-12-21,172.769882,91185900,"[170.9222412109375, 169.53399658203125, 172.76..."
2021-12-22,175.416504,92135300,"[169.53399658203125, 172.76988220214844, 175.4..."
2021-12-23,176.055695,68356600,"[172.76988220214844, 175.41650390625, 176.0556..."
2021-12-27,180.100540,74919600,"[175.41650390625, 176.05569458007812, 180.1005..."
2021-12-28,179.061859,79144300,"[176.05569458007812, 180.1005401611328, 179.06..."
2021-12-29,179.151749,62348900,"[180.1005401611328, 179.06185913085938, 179.15..."
2021-12-30,177.973251,59773000,"[179.06185913085938, 179.15174865722656, 177.9..."
2021-12-31,177.344055,64062300,"[179.15174865722656, 177.97325134277344, 177.3..."
2022-01-03,181.778397,104487900,"[177.97325134277344, 177.34405517578125, 181.7..."
2022-01-04,179.471344,99310400,"[177.34405517578125, 181.7783966064453, 179.47..."
2022-01-05,174.697418,94537600,"[181.7783966064453, 179.47134399414062, 174.69..."
2022-01-06,171.781143,96904000,"[179.47134399414062, 174.69741821289062, 171.7..."
2022-01-07,171.950928,86580100,"[174.69741821289062, 171.78114318847656, 171.9..."
2022-01-10,171.970901,106765600,"[171.78114318847656, 171.950927734375, 171.970..."
2022-01-11,174.857224,76138300,"[171.950927734375, 171.9709014892578, 174.8572..."
2022-01-12,175.306641,74805200,"[171.9709014892578, 174.8572235107422, 175.306..."
2022-01-13,171.970901,84505800,"[174.8572235107422, 175.306640625, 171.9709014..."
2022-01-14,172.849792,80355000,"[175.306640625, 171.9709014892578, 172.8497924..."
2022-01-18,169.583939,90956700,"[171.9709014892578, 172.84979248046875, 169.58..."
2022-01-19,166.018478,94815000,"[172.84979248046875, 169.5839385986328, 166.01..."
2022-01-20,164.300659,91420500,"[169.5839385986328, 166.0184783935547, 164.300..."
2022-01-21,162.203354,122848900,"[166.0184783935547, 164.3006591796875, 162.203..."
2022-01-24,161.414337,162294600,"[164.3006591796875, 162.20335388183594, 161.41..."
2022-01-25,159.576691,115798400,"[162.20335388183594, 161.41433715820312, 159.5..."
2022-01-26,159.486801,108275300,"[161.41433715820312, 159.57669067382812, 159.4..."
2022-01-27,159.017410,121954600,"[159.57669067382812, 159.48680114746094, 159.0..."
2022-01-28,170.113266,179935700,"[159.48680114746094, 159.0174102783203, 170.11..."
2022-01-31,174.557602,115541600,"[159.0174102783203, 170.11326599121094, 174.55..."
2022-02-01,174.387817,86213900,"[170.11326599121094, 174.55760192871094, 174.3..."
2022-02-02,175.616257,84914300,"[174.55760192871094, 174.3878173828125, 175.61..."
2022-02-03,172.679993,89418100,"[174.3878173828125, 175.6162567138672, 172.679..."
2022-02-04,172.389999,82391400,"[175.6162567138672, 172.67999267578125, 172.38..."
2022-02-07,171.660004,77251200,"[172.67999267578125, 172.38999938964844, 171.6..."
2022-02-08,174.830002,74829200,"[172.38999938964844, 171.66000366210938, 174.8..."
2022-02-09,176.279999,70195600,"[171.66000366210938, 174.8300018310547, 176.27..."
2022-02-10,173.294998,59841088,"[174.8300018310547, 176.27999877929688, 173.29..."

In [9]:
x = [1, 2, 3]
y = [2, 4, 6]
slope = np.polyfit(x,y,1)[0]
slope

1.9999999999999996

In [10]:
def slope3(x, y):
    return np.polyfit(x, y, 1)[0]

In [11]:
df_sample['slope3'] = df_sample.iloc[2:].apply(lambda x: slope3(x.roll, [-1, 0, 1]), axis=1)

In [12]:
df_sample

,Close,Volume,roll,slope3
Date,,,,
2021-12-16,172.040802,150185800,[172.04080200195312],NaN
2021-12-17,170.922241,195432700,"[172.04080200195312, 170.9222412109375]",NaN
2021-12-20,169.533997,107499100,"[172.04080200195312, 170.9222412109375, 169.53...",-0.794762
2021-12-21,172.769882,91185900,"[170.9222412109375, 169.53399658203125, 172.76...",0.350553
2021-12-22,175.416504,92135300,"[169.53399658203125, 172.76988220214844, 175.4...",0.338858
2021-12-23,176.055695,68356600,"[172.76988220214844, 175.41650390625, 176.0556...",0.541328
2021-12-27,180.100540,74919600,"[175.41650390625, 176.05569458007812, 180.1005...",0.363014
2021-12-28,179.061859,79144300,"[176.05569458007812, 180.1005401611328, 179.06...",0.340621
2021-12-29,179.151749,62348900,"[180.1005401611328, 179.06185913085938, 179.15...",-1.432395
2021-12-30,177.973251,59773000,"[179.06185913085938, 179.15174865722656, 177.9...",-1.264841
2021-12-31,177.344055,64062300,"[179.15174865722656, 177.97325134277344, 177.3...",-1.073346
2022-01-03,181.778397,104487900,"[177.97325134277344, 177.34405517578125, 181.7...",0.330514
2022-01-04,179.471344,99310400,"[177.34405517578125, 181.7783966064453, 179.47...",0.216252
2022-01-05,174.697418,94537600,"[181.7783966064453, 179.47134399414062, 174.69...",-0.271464
2022-01-06,171.781143,96904000,"[179.47134399414062, 174.69741821289062, 171.7...",-0.255109
2022-01-07,171.950928,86580100,"[174.69741821289062, 171.78114318847656, 171.9...",-0.512510
2022-01-10,171.970901,106765600,"[171.78114318847656, 171.950927734375, 171.970...",8.726665
2022-01-11,174.857224,76138300,"[171.950927734375, 171.9709014892578, 174.8572...",0.519668
2022-01-12,175.306641,74805200,"[171.9709014892578, 174.8572235107422, 175.306...",0.509014
2022-01-13,171.970901,84505800,"[174.8572235107422, 175.306640625, 171.9709014...",-0.440436
2022-01-14,172.849792,80355000,"[175.306640625, 171.9709014892578, 172.8497924...",-0.410942
2022-01-18,169.583939,90956700,"[171.9709014892578, 172.84979248046875, 169.58...",-0.417889
2022-01-19,166.018478,94815000,"[172.84979248046875, 169.5839385986328, 166.01...",-0.292582
2022-01-20,164.300659,91420500,"[169.5839385986328, 166.0184783935547, 164.300...",-0.363725
2022-01-21,162.203354,122848900,"[166.0184783935547, 164.3006591796875, 162.203...",-0.522506
2022-01-24,161.414337,162294600,"[164.3006591796875, 162.20335388183594, 161.41...",-0.648510
2022-01-25,159.576691,115798400,"[162.20335388183594, 161.41433715820312, 159.5...",-0.723011
2022-01-26,159.486801,108275300,"[161.41433715820312, 159.57669067382812, 159.4...",-0.814404
2022-01-27,159.017410,121954600,"[159.57669067382812, 159.48680114746094, 159.0...",-3.100210
2022-01-28,170.113266,179935700,"[159.48680114746094, 159.0174102783203, 170.11...",0.134933
2022-01-31,174.557602,115541600,"[159.0174102783203, 170.11326599121094, 174.55...",0.121292
2022-02-01,174.387817,86213900,"[170.11326599121094, 174.55760192871094, 174.3...",0.336997
2022-02-02,175.616257,84914300,"[174.55760192871094, 174.3878173828125, 175.61...",1.194582
2022-02-03,172.679993,89418100,"[174.3878173828125, 175.6162567138672, 172.679...",-0.392682
2022-02-04,172.389999,82391400,"[175.6162567138672, 172.67999267578125, 172.38...",-0.506358
2022-02-07,171.660004,77251200,"[172.67999267578125, 172.38999938964844, 171.6...",-1.846282
2022-02-08,174.830002,74829200,"[172.38999938964844, 171.66000366210938, 174.8...",0.442687
2022-02-09,176.279999,70195600,"[171.66000366210938, 174.8300018310547, 176.27...",0.413784
2022-02-10,173.294998,59841088,"[174.8300018310547, 176.27999877929688, 173.29...",-0.344456

In [13]:
[x for x in range(1, 4)]

[1, 2, 3]

In [14]:
len([x for x in range(-10,11)])

21

In [15]:
from src import functions as fn

In [23]:
stock = 'aapl'
start_date = '12/12/1980'
days_ahead = 1
X_train, X_test, y_train, y_test, stock_df, current_price = f.data(stock, start_date, days_ahead)

In [24]:
stock_df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,month,dayofweek,oc,...,slope3,roll5,slope5,roll9,slope9,roll13,slope13,roll21,slope21,direction
Date,,,,,,,,,,,,,,,,,,,,,
1981-01-14,0.106869,0.107305,0.106869,0.106869,14291200,0.0,0.0,1,2,0.000000e+00,...,-0.001745,"[0.10556044429540634, 0.11123068630695343, 0.1...",-0.000218,"[0.12039108574390411, 0.11777407675981522, 0.1...",-0.001483,"[0.1238805279135704, 0.1256251186132431, 0.122...",-0.001704,"[0.0950915664434433, 0.08811209350824356, 0.09...",0.000852,1
1981-01-15,0.109050,0.109922,0.109050,0.109050,14067200,0.0,0.0,1,3,1.272609e-16,...,0.001309,"[0.11123068630695343, 0.1103583499789238, 0.10...",-0.000785,"[0.11777407675981522, 0.11253920942544937, 0.1...",-0.000829,"[0.1256251186132431, 0.1225719153881073, 0.119...",-0.001531,"[0.08811209350824356, 0.09029291570186615, 0.0...",0.000669,-1
1981-01-16,0.108614,0.108614,0.108178,0.108178,13395200,0.0,0.0,1,4,-4.015831e-03,...,0.000654,"[0.1103583499789238, 0.10643285512924194, 0.10...",-0.000174,"[0.11253920942544937, 0.1077413484454155, 0.10...",-0.000262,"[0.1225719153881073, 0.11908258497714996, 0.12...",-0.001239,"[0.09029291570186615, 0.0929107666015625, 0.09...",0.000357,1
1981-01-19,0.114720,0.115156,0.114720,0.114720,41574400,0.0,0.0,1,0,0.000000e+00,...,0.002835,"[0.10643285512924194, 0.10686898976564407, 0.1...",0.001788,"[0.1077413484454155, 0.10556044429540634, 0.11...",0.000465,"[0.11908258497714996, 0.12039108574390411, 0.1...",-0.000753,"[0.0929107666015625, 0.09858093410730362, 0.10...",0.000141,-1
1981-01-20,0.111667,0.111667,0.111231,0.111231,30083200,0.0,0.0,1,1,-3.906030e-03,...,0.001527,"[0.10686898976564407, 0.10904985666275024, 0.1...",0.001439,"[0.10556044429540634, 0.11123068630695343, 0.1...",0.000523,"[0.12039108574390411, 0.11777407675981522, 0.1...",-0.000472,"[0.09858093410730362, 0.10337883979082108, 0.1...",-0.000125,1

In [25]:
stock_df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'month', 'dayofweek', 'oc', 'hl', 'adj', '8stdev_adj', '8sma_adj',
       '8sma_close', '13stdev_adj', '13sma_adj', '13sma_close', '21stdev_adj',
       '21sma_adj', '21sma_close', 'roll3', 'slope3', 'roll5', 'slope5',
       'roll9', 'slope9', 'roll13', 'slope13', 'roll21', 'slope21',
       'direction'],
      dtype='object')

In [27]:
stock_df[['slope3', 'slope5', 'slope9', 'slope13', 'slope21']].iloc[:5]

              slope3    slope5    slope9   slope13   slope21
Date
1981-01-14 -0.001745 -0.000218 -0.001483 -0.001704  0.000852
1981-01-15  0.001309 -0.000785 -0.000829 -0.001531  0.000669
1981-01-16  0.000654 -0.000174 -0.000262 -0.001239  0.000357
1981-01-19  0.002835  0.001788  0.000465 -0.000753  0.000141
1981-01-20  0.001527  0.001439  0.000523 -0.000472 -0.000125